# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DatingAppScreens' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'GoogleSignIn'
  
  pod 'GoogleSignInSwiftSupport'

  # Pods for DatingAppScreens

  target 'DatingAppScreensTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DatingAppScreensUITests' do
    # Pods for testing
  end

end
