# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '16.0'
target 'DatingAppScreens' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'GoogleSignIn'
  
  pod 'GoogleSignInSwiftSupport'

  # Pods for DatingAppScreens
  
  
   pod 'Socket.IO-Client-Swift', '~> 16.0.1'
   pod 'Starscream', '<= 4.0.4' # Specify a version that supports iOS 10.0
   
   pod 'FacebookLogin'
   
end

target 'DatingAppScreensTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'DatingAppScreensUITests' do
  # Pods for testing
end

